# For more info on HTTP files go to https://aka.ms/vs/httpfile
@GaussianMVC_HostAddress = https://localhost:7056

###

POST {{GaussianMVC_HostAddress}}/api/authentication/token
Content-Type: application/json

{
  //TokenRequest
}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Home

###

GET {{GaussianMVC_HostAddress}}/api/v1/Home/About

###

GET {{GaussianMVC_HostAddress}}/api/v1/Home/Privacy

###

GET {{GaussianMVC_HostAddress}}/api/v1/Home/Contact

###

GET {{GaussianMVC_HostAddress}}/api/v1/Home/Error

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //RoleData
}

###

DELETE {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{id}}
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{id}}
Authorization: Bearer {{$bearerToken}}

###

PUT {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@roleId=string
DELETE {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{roleId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{roleId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/Identity/Roles/{{roleId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Users
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/Identity/Users
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //UserData
}

###

DELETE {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{id}}
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{id}}
Authorization: Bearer {{$bearerToken}}

###

PUT {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@userId=string
DELETE {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

PUT {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Claims
Authorization: Bearer {{$bearerToken}}

###

DELETE {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Roles
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Roles
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/Identity/Users/{{userId}}/Roles
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/BaseMethods
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //BaseMethodSimpleModel
}

###

GET {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/Family
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/Full
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/Simple
Authorization: Bearer {{$bearerToken}}

###

DELETE {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/{{id}}
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/{{id}}
Authorization: Bearer {{$bearerToken}}

###

PUT {{GaussianMVC_HostAddress}}/api/v1/BaseMethods/{{id}}
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/CalculationTypes
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/CalculationTypes
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //CalculationTypeFullModel
}

###

@id=0
GET {{GaussianMVC_HostAddress}}/api/v1/CalculationTypes/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@id=0
PUT {{GaussianMVC_HostAddress}}/api/v1/CalculationTypes/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@id=0
DELETE {{GaussianMVC_HostAddress}}/api/v1/CalculationTypes/{{id}}
Authorization: Bearer {{$bearerToken}}

###

GET {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies
Authorization: Bearer {{$bearerToken}}

###

POST {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //MethodFamilyFullModel
}

###

GET {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies/List
Authorization: Bearer {{$bearerToken}}

###

@id=0
GET {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@id=0
PUT {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies/{{id}}
Authorization: Bearer {{$bearerToken}}

###

@id=0
DELETE {{GaussianMVC_HostAddress}}/api/v1/MethodFamilies/{{id}}
Authorization: Bearer {{$bearerToken}}

###
