CREATE TABLE [dbo].[CalculationTypes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(200) NOT NULL,
	[Keyword] NVARCHAR(20) NOT NULL,
	[DescriptionRtf] NVARCHAR(MAX) NULL,
	[DescriptionText] NVARCHAR(2000) NULL,
	[CreatedDate] DATETIME2(7) NOT NULL DEFAULT (GETUTCDATE()),
	[LastUpdatedDate] DATETIME2(7) NOT NULL DEFAULT (GETUTCDATE()),
	[Archived] BIT NOT NULL DEFAULT 0,
	CONSTRAINT [PK_CalculationTypes] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [UQ_CalculationTypes_Name] UNIQUE NONCLUSTERED ([Keyword] ASC)
)
