//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaussianMVCLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaussianMVCLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_Create.
        /// </summary>
        internal static string BaseMethodsCreate {
            get {
                return ResourceManager.GetString("BaseMethodsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_Delete.
        /// </summary>
        internal static string BaseMethodsDelete {
            get {
                return ResourceManager.GetString("BaseMethodsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_GetAll.
        /// </summary>
        internal static string BaseMethodsGetAll {
            get {
                return ResourceManager.GetString("BaseMethodsGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_GetById.
        /// </summary>
        internal static string BaseMethodsGetById {
            get {
                return ResourceManager.GetString("BaseMethodsGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_GetByMethodFamilyId.
        /// </summary>
        internal static string BaseMethodsGetByMethodFamilyId {
            get {
                return ResourceManager.GetString("BaseMethodsGetByMethodFamilyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_GetList.
        /// </summary>
        internal static string BaseMethodsGetList {
            get {
                return ResourceManager.GetString("BaseMethodsGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spBaseMethods_Update.
        /// </summary>
        internal static string BaseMethodsUpdate {
            get {
                return ResourceManager.GetString("BaseMethodsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Create.
        /// </summary>
        internal static string CalculationTypesCreate {
            get {
                return ResourceManager.GetString("CalculationTypesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Delete.
        /// </summary>
        internal static string CalculationTypesDelete {
            get {
                return ResourceManager.GetString("CalculationTypesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_GetAll.
        /// </summary>
        internal static string CalculationTypesGetAll {
            get {
                return ResourceManager.GetString("CalculationTypesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_GetById.
        /// </summary>
        internal static string CalculationTypesGetById {
            get {
                return ResourceManager.GetString("CalculationTypesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Update.
        /// </summary>
        internal static string CalculationTypesUpdate {
            get {
                return ResourceManager.GetString("CalculationTypesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GaussianData.
        /// </summary>
        internal static string DataDatabaseConnectionString {
            get {
                return ResourceManager.GetString("DataDatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_Create.
        /// </summary>
        internal static string ElectronicStatesCreate {
            get {
                return ResourceManager.GetString("ElectronicStatesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_Delete.
        /// </summary>
        internal static string ElectronicStatesDelete {
            get {
                return ResourceManager.GetString("ElectronicStatesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_GetAll.
        /// </summary>
        internal static string ElectronicStatesGetAll {
            get {
                return ResourceManager.GetString("ElectronicStatesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_GetById.
        /// </summary>
        internal static string ElectronicStatesGetById {
            get {
                return ResourceManager.GetString("ElectronicStatesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_GetList.
        /// </summary>
        internal static string ElectronicStatesGetList {
            get {
                return ResourceManager.GetString("ElectronicStatesGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_Create.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesCreate {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_Delete.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesDelete {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetAll.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetAll {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetByElectronicStateId.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetByElectronicStateId {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetByElectronicStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetByElectronicStateIdAndMethodFamilyId.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetByElectronicStateIdAndMethodFamilyId {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetByElectronicStateIdAndMethodFamilyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetById.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetById {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetByMethodFamilyId.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetByMethodFamilyId {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetByMethodFamilyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_GetList.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesGetList {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStatesMethodFamilies_Update.
        /// </summary>
        internal static string ElectronicStatesMethodFamiliesUpdate {
            get {
                return ResourceManager.GetString("ElectronicStatesMethodFamiliesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spElectronicStates_Update.
        /// </summary>
        internal static string ElectronicStatesUpdate {
            get {
                return ResourceManager.GetString("ElectronicStatesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Create.
        /// </summary>
        internal static string MethodFamiliesCreate {
            get {
                return ResourceManager.GetString("MethodFamiliesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Delete.
        /// </summary>
        internal static string MethodFamiliesDelete {
            get {
                return ResourceManager.GetString("MethodFamiliesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_GetAll.
        /// </summary>
        internal static string MethodFamiliesGetAll {
            get {
                return ResourceManager.GetString("MethodFamiliesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_GetById.
        /// </summary>
        internal static string MethodFamiliesGetById {
            get {
                return ResourceManager.GetString("MethodFamiliesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_GetList.
        /// </summary>
        internal static string MethodFamiliesGetList {
            get {
                return ResourceManager.GetString("MethodFamiliesGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Update.
        /// </summary>
        internal static string MethodFamiliesUpdate {
            get {
                return ResourceManager.GetString("MethodFamiliesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_Create.
        /// </summary>
        internal static string SpinStatesCreate {
            get {
                return ResourceManager.GetString("SpinStatesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_Delete.
        /// </summary>
        internal static string SpinStatesDelete {
            get {
                return ResourceManager.GetString("SpinStatesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_Create.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesCreate {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_Delete.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesDelete {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetAll.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetAll {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetByElectronicStateMethodFamilyId.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetByElectronicStateMethodFamilyId {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetByElectronicStateMethodFamilyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetByElectronicStateIdMethodFamilyIdAndSpinStateId.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetByElectronicStateMethodFamilyIdAndSpinStateId {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetByElectronicStateMethodFamilyIdAndSpin" +
                        "StateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetById.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetById {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetBySpinStateId.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetBySpinStateId {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetBySpinStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_GetList.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesGetList {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStatesElectronicStatesMethodFamilies_Update.
        /// </summary>
        internal static string SpinStatesElectronicStatesMethodFamiliesUpdate {
            get {
                return ResourceManager.GetString("SpinStatesElectronicStatesMethodFamiliesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_GetAll.
        /// </summary>
        internal static string SpinStatesGetAll {
            get {
                return ResourceManager.GetString("SpinStatesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_GetById.
        /// </summary>
        internal static string SpinStatesGetById {
            get {
                return ResourceManager.GetString("SpinStatesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_GetList.
        /// </summary>
        internal static string SpinStatesGetList {
            get {
                return ResourceManager.GetString("SpinStatesGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spSpinStates_Update.
        /// </summary>
        internal static string SpinStatesUpdate {
            get {
                return ResourceManager.GetString("SpinStatesUpdate", resourceCulture);
            }
        }
    }
}
