//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaussianMVCLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaussianMVCLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Create.
        /// </summary>
        internal static string CalculationTypesCreate {
            get {
                return ResourceManager.GetString("CalculationTypesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Delete.
        /// </summary>
        internal static string CalculationTypesDelete {
            get {
                return ResourceManager.GetString("CalculationTypesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_GetAll.
        /// </summary>
        internal static string CalculationTypesGetAll {
            get {
                return ResourceManager.GetString("CalculationTypesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_GetById.
        /// </summary>
        internal static string CalculationTypesGetById {
            get {
                return ResourceManager.GetString("CalculationTypesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCalculationTypes_Update.
        /// </summary>
        internal static string CalculationTypesUpdate {
            get {
                return ResourceManager.GetString("CalculationTypesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GaussianData.
        /// </summary>
        internal static string DataDatabaseConnectionString {
            get {
                return ResourceManager.GetString("DataDatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Create.
        /// </summary>
        internal static string MethodFamiliesCreate {
            get {
                return ResourceManager.GetString("MethodFamiliesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Delete.
        /// </summary>
        internal static string MethodFamiliesDelete {
            get {
                return ResourceManager.GetString("MethodFamiliesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_GetAll.
        /// </summary>
        internal static string MethodFamiliesGetAll {
            get {
                return ResourceManager.GetString("MethodFamiliesGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_GetById.
        /// </summary>
        internal static string MethodFamiliesGetById {
            get {
                return ResourceManager.GetString("MethodFamiliesGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spMethodFamilies_Update.
        /// </summary>
        internal static string MethodFamiliesUpdate {
            get {
                return ResourceManager.GetString("MethodFamiliesUpdate", resourceCulture);
            }
        }
    }
}
